### ISSUE TITLE
Last tab is moved to second place on session restore

### ISSUE THREAD

**Issue by StephGbzh** [sblask/webextension-open-tabs-next-to-current#30]
For several weeks, I've been annoyed by a strange behaviour and finally took the time to look for the cause which happens to be the "Open tabs next to current" extension.

The problem: every time I open Firefox, my previous session is reloaded BUT the last tab is suddenly moved to the second place in the tab bar (very similar to the Closed issue https://github.com/sblask/webextension-open-tabs-next-to-current/issues/28)

It took me a bit of time and patience to find the cause as I have 40+ extensions and had to use dichotomy in deactivating them until the problem disappeared.
To make matter worse, the problem does NOT happen the first time you restart Firefox after you just disabled/enabled/removed/installed any add-on!

Anyway here are simple steps to reproduce it:
1. Create a new profile in Firefox
2. Preferences > General > When Firefox starts: Show your windows and tabs from last time
3. Install add-on "Open Tabs Next to Current"
4. Open 4 tabs with different websites to identify them easily, let's call them A B C D
5. Close & Reopen Firefox: the order is correct: A B C D
6. Close & Reopen Firefox *again*: the order is now A D B C
7. Close & Reopen Firefox *again*: the order is now A C D B
8. and so on...

I'm using Firefox 54 (64 bits) on Ubuntu 17.04 with Open Tabs Next to Current 2.0.8

**Comment by sblask** [comment]
Nothing I can do about this right now. Seems like my hacks don't work good enough and there is no proper way of fixing this. See https://bugzilla.mozilla.org/show_bug.cgi?id=1364019 and my comment there.

**Comment by kparal** [comment]
I have the same problem (FF 57, Fedora 27, OTNTC 2.0.8). It took me several hours to find this report, and I even reported a bug against a wrong extension (https://github.com/piroor/treestyletab/issues/1483). This is still supposed to be not fixed, right?

Could you please reopen this ticket, so that it's clear this is an unresolved bug immediately when looking at this github page? Also, could you please mention it in the readme in the appropriate section? This is pretty much a show-stopper for anyone using TreeStyleTabs, so it would be nice to make it a bit more discoverable.

Also, if there's no proper way to handle this, is it possible to add some hack, e.g. "don't touch the tabs in the first 10 seconds after starting the browser"? Not ideal, but better than nothing. Thanks.

**Comment by kparal** [comment]
Another idea is to detect when too many tabs are opened during a very short time interval (like > 5 tabs in < 0.5 seconds - just random numbers) and ignore those events. Maybe some other extensions (like TST) already have some code working around this problem?

**Comment by piroor** [comment]
Here is a workaround on my addon Tree Style Tab:
https://github.com/piroor/treestyletab/blob/697d62cbe896ac97fbe8c8d19a41232ecec83bfb/webextensions/background/background.js#L70

**Comment by piroor** [comment]
And here is another workaround to detect duplicated/restored tab on tabs.onCreated:
https://github.com/piroor/treestyletab/blob/697d62cbe896ac97fbe8c8d19a41232ecec83bfb/webextensions/common/tree/base.js#L76

This workaround depends on sessions.setTabValue/getTabValue, introduced at Firefox 57.

**Comment by sblask** [comment]
I won't do any hacks, but I might do the session value workaround when I find the time. Not a big fan of using a Chrome incompatible API though.

**Comment by kparal** [comment]
Any ETA for the fix?

**Comment by sblask** [comment]
I uploaded a new beta to https://addons.mozilla.org/en-GB/firefox/addon/open-tabs-next-to-current/versions/beta . I think it does the right thing (if you use Firefox 57). But I could never reproduce this problem reliably, so please have a look and let me know.

**Comment by kparal** [comment]
It seems to be a race condition. With 2.0.10b it's much rarer, but still happens from time to time :/

**Comment by sblask** [comment]
I have a hard time seeing how it could still happen, unless you create loads of tabs and close the browser immediately so the ID can't be saved. Let me know if you find a way to reproduce.

**Comment by kparal** [comment]
> I have a hard time seeing how it could still happen, unless you create loads of tabs and close the browser immediately so the ID can't be saved.

I thought it could be the case, but even when I try, I can't break it now. Hmm. I've also seen the issue multiple times right after upgrading from 2.0.8 to 2.0.10b, but again it's not reliable, and a one-time issue doesn't concern me that much. During standard open up/close browser sequence, I don't seem to be able to break it at the moment. I'll need to use it for a longer time and see. 

Definitely thanks for the fix, though.

**Comment by sblask** [comment]
Fair enough. I think there could be a problem once you install the new version and have existing tabs. It seems random when the extension gets access to tab events (probably because tabs and extensions are loaded concurrently). So some tabs might not cause an event / get the ID and on another start they cause the event I am listening to, don't have the ID and hence are moved. As you said, normal use should not be an issue. I'll go ahead, merge the fix and release a proper version.

**Comment by kparal** [comment]
> I think there could be a problem once you install the new version and have existing tabs. It seems random when the extension gets access to tab events (probably because tabs and extensions are loaded concurrently). So some tabs might not cause an event / get the ID and on another start they cause the event I am listening to, don't have the ID and hence are moved.

That's likely. Maybe you could add ID to all existing tabs when your extension is started, to make sure they're not considered new tabs the next time the browser starts? That could cover this "parallel tabs+extensions startup" loophole.

> I'll go ahead, merge the fix and release a proper version.

Thanks.

**Comment by kparal** [comment]
This is not fixed :/ I upgraded my home computer yesterday from FF56 + tab groups to FF57 + tree style tabs + open tabs next to current. It had 100+ tabs. On the second browser restart the tabs got shifted, probably due to the bug we talked about here, no problem, one time issue. But today, after many more browser restarts, my tabs got shifted again. The browser was running for hours, it was not a "quick startup and shutdown" case. I spent 10 minutes moving the tabs into the correct trees (I have lots of tabs!). I tried two more browser restarts, no issue. I don't know how to trigger this, but it's clearly happening from time to time. Perhaps it's related to tabs that were opened before OTNTC was installed, maybe not. But I simply can't afford to fix my 100 tabs every time this occurs, so I had to disable OTNTC :(

**Comment by kparal** [comment]
Alright, now it happened even with OTNTC disabled. So this time it was not its fault, but probably a fault of tree style tabs. Ugh, I hate this. Sorry for confusion.

**Comment by sblask** [comment]
If you want to open an issue with  them, you can point to this commit I made: https://github.com/sblask/webextension-open-tabs-next-to-current/commit/17a55731752c2be399dd73b47a111eb97be9e335 it sets a ID for all open tabs and whenever a new tab gets opened. Maybe it can be useful to fix the issue...

**Comment by sebma** [comment]
Hi,
It does not seem to be fixed on V2.0.11 with Firefox ESR 52.9.0
Can you reopen this issue ?

**Comment by sblask** [comment]
@sebma Firefox 52 is not supported.

**Comment by sebma** [comment]
@sblask https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/versions/ says : 

Version 2.0.11 Released Nov. 24, 2017 9.4 KiB 
Works with Firefox for Android 51.0 and later, Firefox 51.0 and later

Isn't Firefox 52 later than Firefox 51 ?

**Comment by sblask** [comment]
Yes and it does work. But the fix works only for later versions. Also Firefox 52 is past it's end of life.

**Comment by sebma** [comment]
@sblask I see. My problem is I can't use Firefox-ESR 60 because, 3/4 of the addons I have won't work anymore because they have not been ported and most of them don't have an equivalent.

Do you think you could provide a fix for Firefox-ESR 52 as well ?

**Comment by sblask** [comment]
No, it requires an API that is not available in 52.

**Comment by sebma** [comment]
@sblask OK, I understand I'll switch to "tab mix plus" instead. It contains the same functionality (among others) without this bug.
Thanks a lot for your help :-)
Cheers.
